### ISSUE TITLE
popwindow里面使用你的控件，气泡不会消失

### ISSUE THREAD

**Issue by ZhangZhengPeng** [yujinzhao123/DoubleHeadedDragonBar#2]
![image](https://user-images.githubusercontent.com/23691922/54997336-708faa00-5006-11e9-8cca-48e66620db21.png)
![image](https://user-images.githubusercontent.com/23691922/54997349-78e7e500-5006-11e9-82bc-023ca32ca98d.png)

**Comment by yujinzhao123** [comment]
增加了close()方法，手动隐藏气泡 1.0.5版本
